"""book table

Revision ID: 8be8b3e42445
Revises: 
Create Date: 2021-07-31 13:48:55.641343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be8b3e42445'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('authors_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('second_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('authors_id')
    )
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('release_year', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('author',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('authors_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authors_id'], ['authors.authors_id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    op.drop_table('book')
    op.drop_table('authors')
    # ### end Alembic commands ###
